version: "3.9"
services:
  api:
    build: .
    container_name: ml-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
      - ./app/data:/app/app/data
      - ./app/models:/app/app/models
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped


